### ISSUE TITLE
Problems with 2 screens

### ISSUE THREAD

**Issue by EloiSanchez** [bigbigmdm/GAOMON-S620-in-LINUX#1]
Hi

Is there any way to configure the table to just use the principal screen?

I usually have my note-taking software in the principal screen and other things in the secondary one. Now I am effectively loosing my left half of the tablet area.

Thanks!

**Comment by bigbigmdm** [comment]
I'm sorry! I have never worked with using two displays on a Linux system. I don't know how to do it ...
It may be possible to find information about the "xsetwacom" command for the two screens in the Wiki: https://wiki.archlinux.org/title/wacom_tablet

**Comment by EloiSanchez** [comment]
Indeed, the info was there. Thanks!

I have not been able to automatically execute the configuration script when plugging in the tablet, but this is another issue.
