### ISSUE TITLE
Gaomon S620

### ISSUE THREAD

**Issue by csc840219** [bigbigmdm/GAOMON-S620-in-LINUX#2]
Hello.
I've been trying to make my S620 works on linux.
Do you install some driver befor the steps you show here?
I'm using elementary os 6.0 with kernel 5.11.
Thanks for your help and sorry, I knoe this is mot am issue, just a question about "how to", but I didn't know where to ask.

**Comment by bigbigmdm** [comment]
Hello! No, I only do what I posted in the article. Look at the output of the lsusb command and see  the configuration file /usr/share/X11/xorg.conf.d/70-wacom.conf

**Comment by csc840219** [comment]
Hello again.
Thank you so much. It works perfect. There is just one mistake. You wrote: 'InputClass" section', but it must be: 'section "InputClass"'.

**Comment by bigbigmdm** [comment]
Thank you! I changed that line in the configuration file.
